/* tslint:disable */
/* eslint-disable */
/**
 * Georgia_Tech_Library_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Catalog,
} from '../models';

export interface ApiCatalogGetListBatchNumberGetRequest {
    batchNumber: number;
}

/**
 * CatalogApi - interface
 * 
 * @export
 * @interface CatalogApiInterface
 */
export interface CatalogApiInterface {
    /**
     * 
     * @param {number} batchNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    apiCatalogGetListBatchNumberGetRaw(requestParameters: ApiCatalogGetListBatchNumberGetRequest): Promise<runtime.ApiResponse<Array<Catalog>>>;

    /**
     */
    apiCatalogGetListBatchNumberGet(requestParameters: ApiCatalogGetListBatchNumberGetRequest): Promise<Array<Catalog>>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    apiCatalogGetListGetRaw(): Promise<runtime.ApiResponse<Array<Catalog>>>;

    /**
     */
    apiCatalogGetListGet(): Promise<Array<Catalog>>;

}

/**
 * 
 */
export class CatalogApi extends runtime.BaseAPI implements CatalogApiInterface {

    /**
     */
    async apiCatalogGetListBatchNumberGetRaw(requestParameters: ApiCatalogGetListBatchNumberGetRequest): Promise<runtime.ApiResponse<Array<Catalog>>> {
        if (requestParameters.batchNumber === null || requestParameters.batchNumber === undefined) {
            throw new runtime.RequiredError('batchNumber','Required parameter requestParameters.batchNumber was null or undefined when calling apiCatalogGetListBatchNumberGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Catalog/GetList/{batchNumber}`.replace(`{${"batchNumber"}}`, encodeURIComponent(String(requestParameters.batchNumber))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiCatalogGetListBatchNumberGet(requestParameters: ApiCatalogGetListBatchNumberGetRequest): Promise<Array<Catalog>> {
        const response = await this.apiCatalogGetListBatchNumberGetRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async apiCatalogGetListGetRaw(): Promise<runtime.ApiResponse<Array<Catalog>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Catalog/GetList`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiCatalogGetListGet(): Promise<Array<Catalog>> {
        const response = await this.apiCatalogGetListGetRaw();
        return await response.value();
    }

}
